// ENTHUSIASM
export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;
export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;


// CITY
export const GET_CITIES = 'GET_CITIES';
export type GET_CITIES = typeof GET_CITIES;
export const LOG_CITYNAME = 'LOG_CITYNAME';
export type LOG_CITYNAME = typeof LOG_CITYNAME;
export const GET_CITIES_BEGIN = 'GET_CITIES_BEGIN';
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS';
export const GET_CITIES_ERROR = 'GET_CITIES_ERROR';

// CURRENTUSER
export const GET_CURRENTUSER = 'GET_CURRENTUSER';
export type GET_CURRENTUSER = typeof GET_CURRENTUSER;
export const LOGOUT = 'LOGOUT';
export type LOGOUT = typeof LOGOUT;

export const LOGOUT_BEGIN = 'LOGOUT_BEGIN';
export type LOGOUT_BEGIN = typeof LOGOUT_BEGIN;
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export type LOGOUT_SUCCESS = typeof LOGOUT_SUCCESS;
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export type LOGOUT_ERROR = typeof LOGOUT_ERROR;
